language:
  - java
  - scala

before_install: sudo pip install codecov
script: sbt clean coverage test jacoco:check
jdk:
  - oraclejdk7
scala:
  - 2.11.4

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
git:
  depth: 1
after_success: codecov
